# Generated by Django 3.2.12 on 2026-01-03 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=200, null=True)),
                ('shipper_name', models.CharField(blank=True, max_length=200, null=True)),
                ('shipper_location', models.CharField(blank=True, max_length=200, null=True)),
                ('shipper_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_location', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_freight', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_date', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('package', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier', models.CharField(blank=True, max_length=200, null=True)),
                ('shipment_mode', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.CharField(blank=True, max_length=200, null=True)),
                ('expected_delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('pickup_time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('type_of_shipment', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('departure_time', models.TimeField(default=django.utils.timezone.now)),
                ('piece_type', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('length', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
